/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/carrera-gt/scene.gltf -o app/CarreraGT.tsx 
Author: Ajay Gawde (https://sketchfab.com/aagawde)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/porsche-carrera-gt-low-poly-68570726d7364f81a00d4bf0e448e642
Title: Porsche Carrera GT - Low Poly
*/

import * as THREE from 'three'
import React from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useEffect } from 'react';

export default function CarreraGT(props: JSX.IntrinsicElements['group']) {
  const { nodes, materials } = useGLTF('/carrera-gt/scene.gltf') as any

  useEffect(() => {
    // Loop through all materials to fix the "black void" rendering issue
    Object.values(materials).forEach((material: any) => {
      material.metalness = 0.2; // Drop the metalness so it doesn't absorb all light
      material.roughness = 0.6; // Increase roughness so it catches the ambient lighting
      material.needsUpdate = true; // Force Three.js to re-render the material
    });
  }, [materials]);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]} scale={0.27}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh geometry={nodes.Object_4.geometry} material={materials.Wing} position={[0, 0.001, 0]} />
          <mesh geometry={nodes.Object_6.geometry} material={materials.Glass} />
          <mesh geometry={nodes.Object_7.geometry} material={materials.Light_glass} />
          <mesh geometry={nodes.Object_9.geometry} material={materials.Details} />
          <mesh geometry={nodes.Object_11.geometry} material={materials.Body} />
          <mesh geometry={nodes.Object_13.geometry} material={materials.Caliper} position={[3.263, 1.312, 4.82]} rotation={[-1.678, 0, -Math.PI / 2]} scale={2.488} />
          <mesh geometry={nodes.Object_15.geometry} material={materials.Caliper} position={[-3.26, 1.312, 4.82]} rotation={[1.459, 0, Math.PI / 2]} scale={2.488} />
          <mesh geometry={nodes.Object_17.geometry} material={materials.Caliper} position={[-3.228, 1.386, -5.989]} rotation={[-1.367, 0, Math.PI / 2]} scale={2.65} />
          <mesh geometry={nodes.Object_19.geometry} material={materials.Caliper} position={[3.231, 1.386, -5.989]} rotation={[1.773, 0, -Math.PI / 2]} scale={2.65} />
          <mesh geometry={nodes.Object_21.geometry} material={materials.Roter} position={[3.231, 1.386, -5.989]} rotation={[0, 0, -Math.PI / 2]} scale={2.65} />
          <mesh geometry={nodes.Object_23.geometry} material={materials.Roter} position={[3.263, 1.312, 4.82]} rotation={[-2.676, 0, -Math.PI / 2]} scale={2.488} />
          <mesh geometry={nodes.Object_25.geometry} material={materials.Roter} position={[-3.26, 1.312, 4.82]} rotation={[2.676, 0, Math.PI / 2]} scale={2.488} />
          <mesh geometry={nodes.Object_27.geometry} material={materials.Roter} position={[-3.228, 1.386, -5.989]} rotation={[0, 0, Math.PI / 2]} scale={2.65} />
          <mesh geometry={nodes.Object_29.geometry} material={materials.Wheel_red} position={[3.231, 1.386, -5.989]} rotation={[0, 0, -Math.PI / 2]} scale={2.65} />
          <mesh geometry={nodes.Object_31.geometry} material={materials.Wheel_red} position={[3.263, 1.312, 4.82]} rotation={[-2.676, 0, -Math.PI / 2]} scale={2.488} />
          <mesh geometry={nodes.Object_33.geometry} material={materials.Wheel_Blue} position={[-3.26, 1.312, 4.82]} rotation={[2.676, 0, Math.PI / 2]} scale={2.488} />
          <mesh geometry={nodes.Object_35.geometry} material={materials.Wheel_Blue} position={[-3.228, 1.386, -5.989]} rotation={[0, 0, Math.PI / 2]} scale={2.65} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/carrera-gt/scene.gltf')